
name: Sync with Upstream and Deploy

on:
  schedule:
    - cron: '0 0 * * sun' # At 00:00 on Sunday.
  workflow_dispatch:

jobs:
  sync_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout forked repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up upstream repository
        run: |
          git remote add upstream ${{ secrets.UPSTREAM_REPO_URL }}
          git fetch upstream

      - name: Setup GIT Credentials
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ secrets.COMMIT_EMAIL }}"
          git config user.password "${{ secrets.GITHUB_TOKEN }}"

      - name: Pull and Merge Upstream Changes
        id: merge_upstream
        run: |
          git config pull.rebase true
          git pull upstream main 
          merge_status=$?
          echo "merge_status=$merge_status" >> $GITHUB_OUTPUT

      - name: Push changes to fork
        if: steps.merge_upstream.outputs.merge_status == '0' || success()
        run: |
          git push origin main

      - name: Trigger Re-Deployment
        if: steps.merge_upstream.outputs.merge_status == '0' || success()
        run: curl -X GET "${{ secrets.ORACLE_PROJECT_URL }}"